
elubuntu ansible_host=IP_DE_LA_VM ansible_connection=ssh ansible_user=EL_QUE_SEA
elredhat ansible_host=IP_DE_LA_VM ansible_connection=ssh ansible_user=EL_QUE_SEA


# Algunos tenéis Docker
# Ejecutaremos desde el Windows

# Algunos no teneis docker
# Ejecutaremos desde el redhat que ahí si tenemos docker (en realidad podman)
