
distros_soportadas:
  - Ubuntu
  - Redhat

paquetes:
  - nombre:                 git
    version:                2.40.0 #latest
    version_matching:       major  #minor, major, equals. DEFAULT: EQUALS
    yum:
      repo:
        nombre:             repo-git
        url:
        clave:
    apt: 
      repo:
        nombre:             repo-git
        url:
        clave:
  - nombre:                 curl
    version_matching:       latest  #minor, major, equals. DEFAULT: EQUALS
