- name:               Asegurar que los puertos usados por la app quedan abiertos en el firewall
  community.general.ufw:
    rule:             allow
    port:             "{{configuracion_despliegue_apache.aplicacion.deploy.puerto|default(despliegue_apache_defaults.aplicacion.deploy.puerto)}}"
    proto:            tcp
