- name:                           Asegurar que el repositorio DNF queda registrado si se ha indicado para {{ paquete_efectivo.nombre }}
  ansible.builtin.yum_repository:
    name:                         "{{ paquete_efectivo.repo.nombre }}"
    baseurl:                      "{{ paquete_efectivo.repo.url }}"
    enabled:                      true
    gpgcheck:                     "{{ paquete_efectivo.repo.clave is defined and paquete_efectivo.repo.clave | length > 0 }}"
    gpgkey:                       "{{ paquete_efectivo.repo.clave }}"
    state:                        present
  become: true # Esta es ansible (Ponerme como administrador... usuario privilegiado)
  when: paquete_efectivo.repo | length > 0  # Miramos si hay datos dentro del repo

- name:                           Asegurar que queda instalado el paquete {{ paquete_efectivo.nombre }}
  ansible.builtin.dnf:
    name:                         "{{ paquete_efectivo.nombre }}{{ ('-' + version_final | trim) if version_final | trim else '' }}"
    state:                        present
    update_cache:                 true
    # allow_downgrade: true   A revisar.
  become: true
