# Este es el archivoque debesrellenarparahacertusuper despliegue!
configuracion_despliegue_apache: 
    apache:                 
        version:    # Aqui pones la version del apache que quieres instalar
        yum: 
            paquete:   httpd
            repo:
        apt: 
            paquete:   apache2
            repo:
    aplicacion:
        repo:
            url:
            tag:
        deploy:
            puerto: 80
            fqdn:
            path:   /var/apache/aplicacion
        test:
            endpoint:   /
            statusCode: 200
