- name: Despliegue de Web en Apache
  hosts: all
  #vars:
  #become: true NO LO HACEMOS! Lo pongo siempre a nivel de tarea. Esto es por vaguería
  gather_facts: false

  pre_tasks:
    - name:                           Obtener información necesaria para la ejecución del playbook
      ansible.builtin.import_tasks:   pre-tasks/tareas.carga.datos.yaml
      tags:
          - always
    - name:                           Verificar que es posible la ejecución del playbook con la información suministrada
      ansible.builtin.import_tasks:   pre-tasks/tareas.verificacion.yaml
      tags:
          - always
    - name:                           Asegurar los requisitos necesarios para la ejecución del playbook
      ansible.builtin.import_tasks:   pre-tasks/tareas.requisitos.yaml
      tags:
          - always

  tasks:
    - name:               Despliegue del apache/aplicación
      block:
        - name:                          Instalación apache
          ansible.builtin.include_tasks: "tasks/tareas.instalacion.apache.yaml"
          tags: 
              - instalacion-apache
        - name:                          Despliegue aplicación
          ansible.builtin.import_tasks:  tasks/tareas.despliegue.aplicacion.yaml
          tags:
              - despliegue-aplicacion
        - name:                          Configuración de la aplicación en apache
          ansible.builtin.import_tasks:  tasks/tareas.configuracion.apache.yaml
          tags: 
              - configuracion-apache
        - name:                          Configurar conectividad de la aplicación
          ansible.builtin.import_tasks:  tasks/tareas.configuracion.firewall.yaml
          tags: 
              - configuracion-firewall
      rescue:
        - name:             Notificar error en despliegue
          changed_when:     true
          notify:           ERROR_EN_DESPIEGUE

  post_tasks:
    - block:
        - name:                           Pruebas del servidor web y la app
          ansible.builtin.import_tasks:   post-tasks/pruebas.yaml
          tags:
              - test
              - always
      rescue:
        - name:             Notificar error en despliegue
          changed_when:     true
          notify:           ERROR_EN_DESPIEGUE

  handlers:
    - name:                           Asegurar que el servicio de apache queda reiniciado
      ansible.builtin.import_tasks:   handlers/servicio.apache.yaml

    - name:                           Notificar problema
      ansible.builtin.import_tasks:   handlers/notificacion.errores.yaml
