- name: Despliegue de Web en Apache
  hosts: all
  #vars:

  gather_facts: false

  pre_tasks:
    # Carga de datos
    - name:               Cargar datos necesarios para la ejecución del playbook
    - name:               Obtener el Sistema Operativo destino
    # Verificaciones
    - name:               Asegurar compatibilidad del playbook con el Sistema Operativo destino
    - name:               Verificar que las variables tienen información adecuada
    # Requisitos
    - name:               Asegurar que está instalada la paquetería necesaria para el playbook

  tasks:
    - name:               Despliegue de la aplicación
      block:
        - name:                          Instalación apache
          ansible.builtin.import_tasks:  tasks/tareas.instalacion.apache.yaml
          tags: 
              - instalacion-apache
        - name:                          Despliegue aplicación
          ansible.builtin.import_tasks:  tasks/tareas.despliegue.aplicacion.yaml
          tags:
              - despliegue-aplicacion
        - name:                          Configuración de la aplicación en apache
          ansible.builtin.import_tasks:  tasks/tareas.configuracion.apache.yaml
          tags: 
              - configuracion-apache
        - name:                          Configurar conectividad de la aplicación
          ansible.builtin.import_tasks:  tasks/tareas.configuracion.firewall.yaml
          tags: 
              - configuracion-firewall
      rescue:
        - name:             Notificar error en despliegue
          changed_when:     true
          notify:           ERROR_EN_DESPIEGUE

  post_tasks:
    - block:
        - name:                           Pruebas del servidor web y la app
          ansible.builtin.import_tasks:   post-tasks/pruebas.yaml
          tags:
              - test
              - always
      rescue:
        - name:             Notificar error en despliegue
          changed_when:     true
          notify:           ERROR_EN_DESPIEGUE

  handlers:
    - name:                           Asegurar que el servicio de apache queda reiniciado
      ansible.builtin.import_tasks:   handlers/servicio.apache.yaml

    - name:                           Notificar problema
      ansible.builtin.import_tasks:   handlers/notificacion.errores.yaml
